package jako.phase1

import jako.AnalysisResult
import jako.Config
import jako.runners.invokeSkillOneShot
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import kotlin.io.path.exists

/**
 * Phase 1 — KMP scaffolding.
 *
 * Generates `build.gradle.kts` in KMP shape, moves the original `.java`
 * tree into `src/jvmMain/java` (and `src/jvmTest/java` for tests). Nothing
 * here is LLM-driven except an optional one-shot pass over the generated
 * build files with the JetBrains `kotlin-tooling-agp9-migration` skill
 * (only if the project applies an Android plugin).
 *
 * Idempotent: re-running on an already-scaffolded module is a no-op.
 */

data class ScaffoldResult(
    val movedMain: Int,
    val movedTest: Int,
    val buildFile: Path,
    val agp9Invoked: Boolean,
)

private fun moduleRoot(cfg: Config): Path {
    val root = cfg.projectRoot()
    return if (cfg.project.module.isNotBlank() && cfg.project.module != ".")
        root.resolve(cfg.project.module) else root
}

private fun moveTree(src: Path, dst: Path): Int {
    if (!src.exists()) return 0
    if (src.toRealPath() == dst.toAbsolutePath().normalize()) return 0
    Files.createDirectories(dst)
    var count = 0
    Files.walk(src).use { stream ->
        val files = stream.filter { Files.isRegularFile(it) && it.toString().endsWith(".java") }.toList()
        for (path in files) {
            val rel = src.relativize(path)
            val target = dst.resolve(rel)
            Files.createDirectories(target.parent)
            Files.move(path, target, StandardCopyOption.REPLACE_EXISTING)
            count++
        }
    }
    // Sweep empty dirs.
    Files.walk(src).use { stream ->
        stream.sorted(Comparator.reverseOrder())
            .filter { Files.isDirectory(it) }
            .forEach { p -> if (Files.list(p).use { l -> !l.findFirst().isPresent }) Files.deleteIfExists(p) }
    }
    return count
}

private fun renderBuildKts(deps: List<String>, usesAgp: Boolean): String = buildString {
    appendLine("// Generated by jako.phase1.Scaffold.")
    appendLine("// Java production code lives under src/jvmMain/java during the migration;")
    appendLine("// tests stay under src/jvmTest/java until phase 4. Converted Kotlin lives")
    appendLine("// under src/jvmMain/kotlin.")
    appendLine()
    appendLine("plugins {")
    appendLine("    kotlin(\"multiplatform\") version \"2.1.0\"")
    if (usesAgp) appendLine("    id(\"com.android.library\") version \"8.7.0\"")
    appendLine("}")
    appendLine()
    appendLine("kotlin {")
    appendLine("    jvm {")
    appendLine("        compilations.all {")
    appendLine("            kotlinOptions.jvmTarget = \"17\"")
    appendLine("        }")
    appendLine("        withJava()")
    appendLine("    }")
    appendLine()
    appendLine("    sourceSets {")
    appendLine("        val commonMain by getting {")
    appendLine("            dependencies { implementation(kotlin(\"stdlib\")) }")
    appendLine("        }")
    appendLine("        val jvmMain by getting {")
    appendLine("            dependencies {")
    for (d in deps) appendLine("                implementation(\"$d\")")
    appendLine("            }")
    appendLine("        }")
    appendLine("        val commonTest by getting {")
    appendLine("            dependencies { implementation(kotlin(\"test\")) }")
    appendLine("        }")
    appendLine("        val jvmTest by getting {")
    appendLine("            dependencies { implementation(\"org.junit.jupiter:junit-jupiter:5.10.2\") }")
    appendLine("        }")
    appendLine("    }")
    appendLine("}")
    appendLine()
    appendLine("tasks.withType<Test> { useJUnitPlatform() }")
}

fun scaffold(cfg: Config, analysis: AnalysisResult): ScaffoldResult {
    val modRoot = moduleRoot(cfg)

    // 1. Move source trees into KMP layout.
    val movedMain = moveTree(modRoot.resolve("src/main/java"), modRoot.resolve("src/jvmMain/java"))
    val movedTest = moveTree(modRoot.resolve("src/test/java"), modRoot.resolve("src/jvmTest/java"))
    Files.createDirectories(modRoot.resolve("src/jvmMain/kotlin"))

    // 2. Render KMP build file, backing up any existing one.
    val buildFile = modRoot.resolve("build.gradle.kts")
    val legacy = modRoot.resolve("build.gradle")
    if (Files.exists(buildFile)) {
        val backup = modRoot.resolve("build.gradle.kts.pre-kmp.bak")
        if (!Files.exists(backup)) Files.copy(buildFile, backup)
    }
    if (Files.exists(legacy)) {
        val backup = modRoot.resolve("build.gradle.pre-kmp.bak")
        if (!Files.exists(backup)) Files.copy(legacy, backup)
    }
    Files.writeString(
        buildFile,
        renderBuildKts(analysis.buildModel.gradleDependencies, analysis.buildModel.pluginUsesAgp),
    )

    // 3. Optional AGP9 sanity pass.
    var agp9Invoked = false
    if (analysis.buildModel.pluginUsesAgp) {
        val skill = cfg.skillPath(cfg.skills.agp9Migration)
        if (Files.exists(skill)) {
            invokeSkillOneShot(
                cfg,
                skillPath = skill,
                userPrompt = "Apply the AGP 9 migration to this Gradle module. " +
                    "Working directory: $modRoot. Only edit build files. Do not deliberate.",
                cwd = modRoot,
            )
            agp9Invoked = true
        }
    }

    return ScaffoldResult(
        movedMain = movedMain,
        movedTest = movedTest,
        buildFile = buildFile,
        agp9Invoked = agp9Invoked,
    )
}

fun runScaffold(cfg: Config, analysis: AnalysisResult): ScaffoldResult {
    val res = scaffold(cfg, analysis)
    println("[scaffold] moved ${res.movedMain} main + ${res.movedTest} test files into KMP layout")
    println("[scaffold] wrote ${res.buildFile}")
    if (res.agp9Invoked) println("[scaffold] AGP9 migration skill applied")
    return res
}
