package jako.phase1

import jako.AnalysisResult
import jako.Config
import jako.GradleDep
import jako.runners.invokeSkillOneShot
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import kotlin.io.path.exists

/**
 * Phase 1 — KMP scaffolding.
 *
 * Generates `build.gradle.kts` in KMP shape, moves the original `.java`
 * tree into `src/jvmMain/java` (and `src/jvmTest/java` for tests). Nothing
 * here is LLM-driven except an optional one-shot pass over the generated
 * build files with the JetBrains `kotlin-tooling-agp9-migration` skill
 * (only if the project applies an Android plugin).
 *
 * Idempotent: re-running on an already-scaffolded module is a no-op.
 */

data class ScaffoldResult(
    val movedMain: Int,
    val movedTest: Int,
    val buildFile: Path,
    val agp9Invoked: Boolean,
)

private fun moduleRoot(cfg: Config): Path {
    val root = cfg.projectRoot()
    return if (cfg.project.module.isNotBlank() && cfg.project.module != ".")
        root.resolve(cfg.project.module) else root
}

private fun moveTree(src: Path, dst: Path): Int {
    if (!src.exists()) return 0
    if (src.toRealPath() == dst.toAbsolutePath().normalize()) return 0
    Files.createDirectories(dst)
    var count = 0
    Files.walk(src).use { stream ->
        val files = stream.filter { Files.isRegularFile(it) && it.toString().endsWith(".java") }.toList()
        for (path in files) {
            val rel = src.relativize(path)
            val target = dst.resolve(rel)
            Files.createDirectories(target.parent)
            Files.move(path, target, StandardCopyOption.REPLACE_EXISTING)
            count++
        }
    }
    // Sweep empty dirs.
    Files.walk(src).use { stream ->
        stream.sorted(Comparator.reverseOrder())
            .filter { Files.isDirectory(it) }
            .forEach { p -> if (Files.list(p).use { l -> !l.findFirst().isPresent }) Files.deleteIfExists(p) }
    }
    return count
}

/**
 * Generate a Kotlin-DSL build file that uses the JVM Kotlin plugin already
 * supplied by the parent project's `allprojects { apply plugin: 'kotlin' }`
 * (the common case for multi-project Gradle repos). We override `main` and
 * `test` source sets to point at `src/jvmMain/{java,kotlin}` and
 * `src/jvmTest/{java,kotlin}` — KMP-style layout, JVM-only plugin.
 *
 * The real `kotlin("multiplatform")` plugin is deferred to phase 3 (M6),
 * when `commonMain` becomes relevant. Re-applying it here would collide
 * with the parent's JVM plugin on most real-world multi-project builds
 * (parent applies `apply plugin: 'kotlin'` + `apply plugin: 'java-library'`,
 * both of which clash with KMP's `withJava()` integration).
 *
 * Each dep is emitted in the Gradle configuration it was originally
 * declared in (api / implementation / compileOnly / runtimeOnly /
 * testImplementation / testCompileOnly / testRuntimeOnly / annotationProcessor).
 */
private fun renderBuildKts(deps: List<GradleDep>, usesAgp: Boolean): String = buildString {
    appendLine("// Generated by jako.phase1.Scaffold.")
    appendLine("//")
    appendLine("// Uses the JVM Kotlin plugin applied by the parent project's allprojects")
    appendLine("// block. Source dirs are overridden to the KMP layout (jvmMain/jvmTest).")
    appendLine("// The real kotlin(\"multiplatform\") plugin is deferred to phase 3.")
    appendLine()
    if (usesAgp) {
        appendLine("plugins {")
        appendLine("    id(\"com.android.library\")")
        appendLine("}")
        appendLine()
    }
    appendLine("sourceSets {")
    appendLine("    named(\"main\") {")
    appendLine("        java.setSrcDirs(listOf(\"src/jvmMain/java\"))")
    appendLine("        resources.setSrcDirs(listOf(\"src/jvmMain/resources\"))")
    appendLine("    }")
    appendLine("    named(\"test\") {")
    appendLine("        java.setSrcDirs(listOf(\"src/jvmTest/java\"))")
    appendLine("        resources.setSrcDirs(listOf(\"src/jvmTest/resources\"))")
    appendLine("    }")
    appendLine("}")
    appendLine()
    appendLine("extensions.configure<org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension>(\"kotlin\") {")
    appendLine("    sourceSets.named(\"main\") {")
    appendLine("        kotlin.setSrcDirs(listOf(\"src/jvmMain/kotlin\"))")
    appendLine("    }")
    appendLine("    sourceSets.named(\"test\") {")
    appendLine("        kotlin.setSrcDirs(listOf(\"src/jvmTest/kotlin\"))")
    appendLine("    }")
    appendLine("}")
    if (deps.isNotEmpty()) {
        appendLine()
        appendLine("dependencies {")
        // The string-config form `"configuration"("coord")` works uniformly
        // for any configuration name, including ones the Kotlin DSL doesn't
        // generate static accessors for (e.g. `annotationProcessor` on
        // modules without the `java` plugin applied at the subproject level).
        for (d in deps) appendLine("    \"${d.configuration}\"(\"${d.coordinate}\")")
        appendLine("}")
    }
}

fun scaffold(cfg: Config, analysis: AnalysisResult): ScaffoldResult {
    val modRoot = moduleRoot(cfg)

    // 1. Move source trees into KMP layout.
    val movedMain = moveTree(modRoot.resolve("src/main/java"), modRoot.resolve("src/jvmMain/java"))
    val movedTest = moveTree(modRoot.resolve("src/test/java"), modRoot.resolve("src/jvmTest/java"))
    Files.createDirectories(modRoot.resolve("src/jvmMain/kotlin"))

    // 2. Render KMP build file, backing up any existing one.
    val buildFile = modRoot.resolve("build.gradle.kts")
    val legacy = modRoot.resolve("build.gradle")
    if (Files.exists(buildFile)) {
        val backup = modRoot.resolve("build.gradle.kts.pre-kmp.bak")
        if (!Files.exists(backup)) Files.copy(buildFile, backup)
    }
    if (Files.exists(legacy)) {
        val backup = modRoot.resolve("build.gradle.pre-kmp.bak")
        if (!Files.exists(backup)) Files.copy(legacy, backup)
        // Gradle prefers `build.gradle` over `build.gradle.kts` when both
        // exist; leaving the legacy file in place would silently keep using
        // the pre-KMP Groovy config. Remove it after backup.
        Files.delete(legacy)
    }
    Files.writeString(
        buildFile,
        renderBuildKts(analysis.buildModel.gradleDependencies, analysis.buildModel.pluginUsesAgp),
    )

    // 3. Optional AGP9 sanity pass.
    var agp9Invoked = false
    if (analysis.buildModel.pluginUsesAgp) {
        val skill = cfg.skillPath(cfg.skills.agp9Migration)
        if (Files.exists(skill)) {
            invokeSkillOneShot(
                cfg,
                skillPath = skill,
                userPrompt = "Apply the AGP 9 migration to this Gradle module. " +
                    "Working directory: $modRoot. Only edit build files. Do not deliberate.",
                cwd = modRoot,
            )
            agp9Invoked = true
        }
    }

    return ScaffoldResult(
        movedMain = movedMain,
        movedTest = movedTest,
        buildFile = buildFile,
        agp9Invoked = agp9Invoked,
    )
}

fun runScaffold(cfg: Config, analysis: AnalysisResult): ScaffoldResult {
    val res = scaffold(cfg, analysis)
    println("[scaffold] moved ${res.movedMain} main + ${res.movedTest} test files into KMP layout")
    println("[scaffold] wrote ${res.buildFile}")
    if (res.agp9Invoked) println("[scaffold] AGP9 migration skill applied")
    return res
}
